version: "3.9"

services:
  investment-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"                # Serve directly on VPS port 80
    env_file:
      - .env                   # Use env_file instead of volume to avoid read-only mount error
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - investment-network

  # Optional: Development service
  investment-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"             # Dev server port
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run dev
    profiles:
      - dev
    networks:
      - investment-network

networks:
  investment-network:
    driver: bridge
