services:
  investment-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_APP_API_URL=https://api.trdexa.com
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - investment-network

  # Optional: Add a development service
  investment-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - VITE_APP_API_URL=https://api.trdexa.com
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_APP_API_URL=https://api.trdexa.com
    command: npm run dev
    profiles:
      - dev
    networks:
      - investment-network

networks:
  investment-network:
    driver: bridge
